### ISSUE TITLE
Error 100006 while reading /api/device/signal 

### ISSUE THREAD

**Issue by VOIR-PT** [arska/e3372#19]
I am trying to read the /api/device/signal from my E3372 to pass RSSI RSRQ RSRP SINR over to telegraf / grafana on an RaspberryPi. I tried to insert a POST function to log in with admin admin on the api/user/login, but it's not working. Any ideas?

**Comment by arska** [comment]
Hello @VOIR-PT, thanks for asking and sorry I did not get a notification. I don't have an E3372 device anymore to test and I'm archiving this project now. Best, Aarno
